### ISSUE TITLE
Getting a fatal error after testing persistence

### ISSUE THREAD

**Issue by trtong** [MakeSchool-Tutorials/Habitual-Swift4#7]
<img width="605" alt="screen shot 2018-11-28 at 2 55 42 pm" src="https://user-images.githubusercontent.com/43478529/49178453-d2245e00-f31d-11e8-9d93-4f1a3a3d27d6.png">

Not sure where my problem is coming up. Might be the habit table cell?

**Comment by trtong** [comment]
<img width="580" alt="screen shot 2018-11-28 at 4 19 15 pm" src="https://user-images.githubusercontent.com/43478529/49182858-634d0200-f329-11e8-9f74-f498487cfbb7.png">

Now getting this error

**Comment by amelinagzz** [comment]
Looks like the elements in the cell are not being initialized at all. `self.imageViewIcon` is the thing failing. Make sure you're setting the cell up correctly.

**Comment by trtong** [comment]
I got it to work, you were right! I wasn't linking up the outputs correctly.
